version: "3.9"

services:
  account:
    build: account/.
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
  db:
    image: postgres:16.2-alpine3.19
    restart: always
    container_name: "pulse_db"
    volumes:
      - db_data:${DB_DATA}
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: ${DB_DATA}
volumes:
  db_data: {}