version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: "auth_postgres_db"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    restart: unless-stopped

  test_db:
    image: postgres:latest
    container_name: "auth_postgres_test_db"
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5430:5432"
    restart: unless-stopped

  pgAdmin:
    container_name: "auth_pg-admin"
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 8081
    ports:
      - 8082:8081
    restart: unless-stopped